routes/web.php
<?php

use Illuminate\Http\File;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('privacy-policy', 'App\Http\Controllers\PrivacyController@index');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {  
    Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');

	Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', 'App\Http\Controllers\UserController@index')->name('index');
        Route::get('edit/{user}', 'App\Http\Controllers\UserController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\UserController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\UserController@store')->name('store');
        Route::post('u/{user}/update', 'App\Http\Controllers\UserController@update')->name('update');
        Route::get('d/{user}/delete', 'App\Http\Controllers\UserController@destroy')->name('delete');
    });

    Route::get('profile', 'App\Http\Controllers\ProfileController@edit')->name('profile.edit');
    Route::put('profile', 'App\Http\Controllers\ProfileController@update')->name('profile.update');
    Route::put('profile/password', 'App\Http\Controllers\ProfileController@password')->name('profile.password');

    Route::group(['prefix' => 'words', 'as' => 'words.'], function () {
        Route::get('/', 'App\Http\Controllers\Data\WordController@index')->name('index');
        Route::get('view/{word}', 'App\Http\Controllers\Data\WordController@view')->name('view');
        Route::get('edit/{word}', 'App\Http\Controllers\Data\WordController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\Data\WordController@create')->name('create');
        Route::get('search', 'App\Http\Controllers\Data\WordController@search')->name('search');
        Route::get('find', 'App\Http\Controllers\Data\WordController@find')->name('find');
        Route::post('store', 'App\Http\Controllers\Data\WordController@store')->name('store');
        Route::post('u/{word}/update', 'App\Http\Controllers\Data\WordController@update')->name('update');
        Route::get('d/{word}/delete', 'App\Http\Controllers\Data\WordController@destroy')->name('delete');
    });

    Route::group(['prefix' => 'proverbs', 'as' => 'proverbs.'], function () {
        Route::get('/', 'App\Http\Controllers\Data\ProverbController@index')->name('index');
        Route::get('edit/{proverb}/proverb', 'App\Http\Controllers\Data\ProverbController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\Data\ProverbController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\Data\ProverbController@store')->name('store');
        Route::post('u/{proverb}/update', 'App\Http\Controllers\Data\ProverbController@update')->name('update');
        Route::get('d/{proverb}/delete', 'App\Http\Controllers\Data\ProverbController@destroy')->name('delete');
    });

    Route::group(['prefix' => 'sayings', 'as' => 'sayings.'], function () {
        Route::get('/', 'App\Http\Controllers\Data\SayingController@index')->name('index');
        Route::get('edit/{saying}', 'App\Http\Controllers\Data\SayingController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\Data\SayingController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\Data\SayingController@store')->name('store');
        Route::post('u/{saying}/update', 'App\Http\Controllers\Data\SayingController@update')->name('update');
        Route::get('d/{saying}/delete', 'App\Http\Controllers\Data\SayingController@destroy')->name('delete');
    });

    Route::group(['prefix' => 'idioms', 'as' => 'idioms.'], function () {
        Route::get('/', 'App\Http\Controllers\Data\IdiomController@index')->name('index');
        Route::get('edit/{idiom}', 'App\Http\Controllers\Data\IdiomController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\Data\IdiomController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\Data\IdiomController@store')->name('store');
        Route::post('u/{idiom}/update', 'App\Http\Controllers\Data\IdiomController@update')->name('update');
        Route::get('d/{idiom}/delete', 'App\Http\Controllers\Data\IdiomController@destroy')->name('delete');
    });

    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
        Route::get('/', 'App\Http\Controllers\Trivia\CategoryController@index')->name('index');
        Route::get('edit/{category}', 'App\Http\Controllers\Trivia\CategoryController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\Trivia\CategoryController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\Trivia\CategoryController@store')->name('store');
        Route::post('u/{category}/update', 'App\Http\Controllers\Trivia\CategoryController@update')->name('update');
        Route::get('d/{category}/delete', 'App\Http\Controllers\Trivia\CategoryController@destroy')->name('delete');
    });

    Route::group(['prefix' => 'trivia', 'as' => 'trivia.'], function () {
        Route::get('/', 'App\Http\Controllers\Trivia\TriviaController@index')->name('index');
        Route::get('edit/{trivia}', 'App\Http\Controllers\Trivia\TriviaController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\Trivia\TriviaController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\Trivia\TriviaController@store')->name('store');
        Route::post('u/{trivia}/update', 'App\Http\Controllers\Trivia\TriviaController@update')->name('update');
        Route::get('d/{trivia}/delete', 'App\Http\Controllers\Trivia\TriviaController@destroy')->name('delete');
    });
    
    Route::group(['prefix' => 'questions', 'as' => 'questions.'], function () {
        Route::get('/', 'App\Http\Controllers\Trivia\QuestionController@index')->name('index');
        Route::get('view/{question}', 'App\Http\Controllers\Trivia\QuestionController@view')->name('view');
        Route::get('edit/{question}', 'App\Http\Controllers\Trivia\QuestionController@edit')->name('edit');
        Route::get('create/{word}', 'App\Http\Controllers\Trivia\QuestionController@create')->name('create');
        Route::get('search', 'App\Http\Controllers\Trivia\QuestionController@search')->name('search');
        Route::post('store', 'App\Http\Controllers\Trivia\QuestionController@store')->name('store');
        Route::post('u/{question}/update', 'App\Http\Controllers\Trivia\QuestionController@update')->name('update');
        Route::get('d/{question}/delete', 'App\Http\Controllers\Trivia\QuestionController@destroy')->name('delete');
    });

	Route::get('leaderboard', function () {
        return view('pages.upgrade');
    })->name('leaderboard');
});

Route::get('storage/{filename}', function ($filename) {
    $path = storage_path('public/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

resources/views/layouts/navbars/navbar.blade.php
@auth()
    @include('layouts.navbars.navs.auth')
@endauth
    
@guest()
    @include('layouts.navbars.navs.guest')
@endguest

resources/views/layouts/navbars/sidebar.blade.php
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand pt-0" href="{{ route('home') }}">
            <img src="{{ asset('argon') }}/img/brand/blue.png" class="navbar-brand-img" alt="...">
        </a>
        <!-- User -->
        <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="media align-items-center">
                        <span class="avatar avatar-sm rounded-circle">
                        <img alt="Image placeholder" src="{{ asset('argon') }}/img/theme/team-1-800x800.jpg">
                        </span>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">{{ __('Welcome!') }}</h6>
                    </div>
                    <a href="{{ route('profile.edit') }}" class="dropdown-item">
                        <i class="ni ni-single-02"></i>
                        <span>{{ __('My profile') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-settings-gear-65"></i>
                        <span>{{ __('Settings') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-calendar-grid-58"></i>
                        <span>{{ __('Activity') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-support-16"></i>
                        <span>{{ __('Support') }}</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                        <i class="ni ni-user-run"></i>
                        <span>{{ __('Logout') }}</span>
                    </a>
                </div>
            </li>
        </ul>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="{{ route('home') }}">
                            <img src="{{ asset('argon') }}/img/brand/blue.png">
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <!-- Form -->
            <form class="mt-4 mb-3 d-md-none">
                <div class="input-group input-group-rounded input-group-merge">
                    <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="{{ __('Search') }}" aria-label="Search">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <span class="fa fa-search"></span>
                        </div>
                    </div>
                </div>
            </form>
            <!-- Navigation -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('home') }}">
                        <i class="ni ni-tv-2 text-primary"></i> {{ __('Dashboard') }}
                    </a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link active" href="#navbar-examples" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="navbar-examples">
                      <i class="ni ni-planet text-blue"></i>
                        <span class="nav-link-text" style="color: #f4645f;">{{ __('Kamusi Data') }}</span>
                    </a>

                    <div class="collapse show" id="navbar-examples">
                        <ul class="nav nav-sm flex-column">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('words.index') }}">
                                    {{ __('Words') }}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('proverbs.index') }}">
                                    {{ __('Proverbs') }}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('sayings.index') }}">
                                    {{ __('Sayings') }}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('idioms.index') }}">
                                    {{ __('Idioms') }}
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" href="#navbar-examples" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="navbar-examples">
                      <i class="ni ni-bullet-list-67 text-default"></i>
                        <span class="nav-link-text" style="color: #f4645f;">{{ __('Kamusi Trivia') }}</span>
                    </a>

                    <div class="collapse show" id="navbar-examples">
                        <ul class="nav nav-sm flex-column">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('categories.index') }}">
                                    {{ __('Categories') }}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('questions.index') }}">
                                    {{ __('Questions') }}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('trivia.index') }}">
                                    {{ __('Trivia') }}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('leaderboard') }}">
                                    {{ __('Leaderboard') }}
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('users.index') }}">
                        <i class="ni ni-circle-08 text-pink"></i> {{ __('Users') }}
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/navbars/sidebar2.blade.php
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand pt-0" href="{{ route('home') }}">
            <img src="{{ asset('argon') }}/img/brand/blue.png" class="navbar-brand-img" alt="...">
        </a>
        <!-- User -->
        <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="media align-items-center">
                        <span class="avatar avatar-sm rounded-circle">
                        <img alt="Image placeholder" src="{{ asset('argon') }}/img/theme/team-1-800x800.jpg">
                        </span>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">{{ __('Welcome!') }}</h6>
                    </div>
                    <a href="{{ route('profile.edit') }}" class="dropdown-item">
                        <i class="ni ni-single-02"></i>
                        <span>{{ __('My profile') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-settings-gear-65"></i>
                        <span>{{ __('Settings') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-calendar-grid-58"></i>
                        <span>{{ __('Activity') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-support-16"></i>
                        <span>{{ __('Support') }}</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                        <i class="ni ni-user-run"></i>
                        <span>{{ __('Logout') }}</span>
                    </a>
                </div>
            </li>
        </ul>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="{{ route('home') }}">
                            <img src="{{ asset('argon') }}/img/brand/blue.png">
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <!-- Form -->
            <form class="mt-4 mb-3 d-md-none">
                <div class="input-group input-group-rounded input-group-merge">
                    <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="{{ __('Search') }}" aria-label="Search">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <span class="fa fa-search"></span>
                        </div>
                    </div>
                </div>
            </form>
            <!-- Navigation -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('home') }}">
                        <i class="ni ni-tv-2 text-primary"></i> {{ __('Dashboard') }}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#navbar-examples" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="navbar-examples">
                        <i class="fab fa-laravel" style="color: #f4645f;"></i>
                        <span class="nav-link-text" style="color: #f4645f;">{{ __('Laravel Examples') }}</span>
                    </a>

                    <div class="collapse show" id="navbar-examples">
                        <ul class="nav nav-sm flex-column">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('profile.edit') }}">
                                    {{ __('User profile') }}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('user.index') }}">
                                    {{ __('User Management') }}
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ route('icons') }}">
                        <i class="ni ni-planet text-blue"></i> {{ __('Icons') }}
                    </a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{ route('map') }}">
                        <i class="ni ni-pin-3 text-orange"></i> {{ __('Maps') }}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('table') }}">
                      <i class="ni ni-bullet-list-67 text-default"></i>
                      <span class="nav-link-text">Tables</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <i class="ni ni-circle-08 text-pink"></i> {{ __('Register') }}
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>