routes/web.php
<?php

use Illuminate\Http\File;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('privacy-policy', 'App\Http\Controllers\PrivacyController@index');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {  
    Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');

	Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', 'App\Http\Controllers\UserController@index')->name('index');
        Route::get('edit/{user}', 'App\Http\Controllers\UserController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\UserController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\UserController@store')->name('store');
        Route::post('u/{user}/update', 'App\Http\Controllers\UserController@update')->name('update');
        Route::get('d/{user}/delete', 'App\Http\Controllers\UserController@destroy')->name('delete');
    });

    Route::get('profile', 'App\Http\Controllers\ProfileController@edit')->name('profile.edit');
    Route::put('profile', 'App\Http\Controllers\ProfileController@update')->name('profile.update');
    Route::put('profile/password', 'App\Http\Controllers\ProfileController@password')->name('profile.password');

    Route::group(['prefix' => 'words', 'as' => 'words.'], function () {
        Route::get('/', 'App\Http\Controllers\Data\WordController@index')->name('index');
        Route::get('view/{word}', 'App\Http\Controllers\Data\WordController@view')->name('view');
        Route::get('edit/{word}', 'App\Http\Controllers\Data\WordController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\Data\WordController@create')->name('create');
        Route::get('search', 'App\Http\Controllers\Data\WordController@search')->name('search');
        Route::get('find', 'App\Http\Controllers\Data\WordController@find')->name('find');
        Route::post('store', 'App\Http\Controllers\Data\WordController@store')->name('store');
        Route::post('u/{word}/update', 'App\Http\Controllers\Data\WordController@update')->name('update');
        Route::get('d/{word}/delete', 'App\Http\Controllers\Data\WordController@destroy')->name('delete');
    });

    Route::group(['prefix' => 'proverbs', 'as' => 'proverbs.'], function () {
        Route::get('/', 'App\Http\Controllers\Data\ProverbController@index')->name('index');
        Route::get('edit/{proverb}/proverb', 'App\Http\Controllers\Data\ProverbController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\Data\ProverbController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\Data\ProverbController@store')->name('store');
        Route::post('u/{proverb}/update', 'App\Http\Controllers\Data\ProverbController@update')->name('update');
        Route::get('d/{proverb}/delete', 'App\Http\Controllers\Data\ProverbController@destroy')->name('delete');
    });

    Route::group(['prefix' => 'sayings', 'as' => 'sayings.'], function () {
        Route::get('/', 'App\Http\Controllers\Data\SayingController@index')->name('index');
        Route::get('edit/{saying}', 'App\Http\Controllers\Data\SayingController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\Data\SayingController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\Data\SayingController@store')->name('store');
        Route::post('u/{saying}/update', 'App\Http\Controllers\Data\SayingController@update')->name('update');
        Route::get('d/{saying}/delete', 'App\Http\Controllers\Data\SayingController@destroy')->name('delete');
    });

    Route::group(['prefix' => 'idioms', 'as' => 'idioms.'], function () {
        Route::get('/', 'App\Http\Controllers\Data\IdiomController@index')->name('index');
        Route::get('edit/{idiom}', 'App\Http\Controllers\Data\IdiomController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\Data\IdiomController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\Data\IdiomController@store')->name('store');
        Route::post('u/{idiom}/update', 'App\Http\Controllers\Data\IdiomController@update')->name('update');
        Route::get('d/{idiom}/delete', 'App\Http\Controllers\Data\IdiomController@destroy')->name('delete');
    });

    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
        Route::get('/', 'App\Http\Controllers\Trivia\CategoryController@index')->name('index');
        Route::get('edit/{category}', 'App\Http\Controllers\Trivia\CategoryController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\Trivia\CategoryController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\Trivia\CategoryController@store')->name('store');
        Route::post('u/{category}/update', 'App\Http\Controllers\Trivia\CategoryController@update')->name('update');
        Route::get('d/{category}/delete', 'App\Http\Controllers\Trivia\CategoryController@destroy')->name('delete');
    });

    Route::group(['prefix' => 'trivia', 'as' => 'trivia.'], function () {
        Route::get('/', 'App\Http\Controllers\Trivia\TriviaController@index')->name('index');
        Route::get('edit/{trivia}', 'App\Http\Controllers\Trivia\TriviaController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\Trivia\TriviaController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\Trivia\TriviaController@store')->name('store');
        Route::post('u/{trivia}/update', 'App\Http\Controllers\Trivia\TriviaController@update')->name('update');
        Route::get('d/{trivia}/delete', 'App\Http\Controllers\Trivia\TriviaController@destroy')->name('delete');
    });
    
    Route::group(['prefix' => 'questions', 'as' => 'questions.'], function () {
        Route::get('/', 'App\Http\Controllers\Trivia\QuestionController@index')->name('index');
        Route::get('view/{question}', 'App\Http\Controllers\Trivia\QuestionController@view')->name('view');
        Route::get('edit/{question}', 'App\Http\Controllers\Trivia\QuestionController@edit')->name('edit');
        Route::get('create/{word}', 'App\Http\Controllers\Trivia\QuestionController@create')->name('create');
        Route::get('search', 'App\Http\Controllers\Trivia\QuestionController@search')->name('search');
        Route::post('store', 'App\Http\Controllers\Trivia\QuestionController@store')->name('store');
        Route::post('u/{question}/update', 'App\Http\Controllers\Trivia\QuestionController@update')->name('update');
        Route::get('d/{question}/delete', 'App\Http\Controllers\Trivia\QuestionController@destroy')->name('delete');
    });

	Route::get('leaderboard', function () {
        return view('pages.upgrade');
    })->name('leaderboard');
});

Route::get('storage/{filename}', function ($filename) {
    $path = storage_path('public/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

app/Models/Trivia/Category.php
<?php

namespace App\Models\Trivia;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'number', 'title', 'description', 'icon', 'active',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'words',
    ];

}

app/Models/Trivia/Player.php
<?php

namespace App\Models\Trivia;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Player extends Model
{
    use HasFactory;
}

app/Models/Trivia/Question.php
<?php

namespace App\Models\Trivia;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'userid', 'category', 'level', 'title', 'answer', 'option1', 'option2', 'option3', 'option4',
    ];

}

app/Models/Trivia/Trivia.php
<?php

namespace App\Models\Trivia;

use Illuminate\Database\Eloquent\Model;

class Trivia extends Model
{
     
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'playerid', 'category', 'level', 'questions', 'score'
    ];
    
}

app/Http/Controllers/Api/Trivia/CategoryController.php
<?php

namespace App\Http\Controllers\Api\Trivia;

use App\Models\Trivia\Category;
use App\Http\Controllers\Controller;
use App\Http\Resources\CategoryResource;
use Symfony\Component\HttpFoundation\Response;

class CategoryController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $results = Category::where('active', '=', 1)->get();

        if (!$results)
            return response([
                'status' => 0,
                'message' => 'Retrieval unsuccessful',
            ], Response::HTTP_BAD_REQUEST);
        else
            return response([
                'status' => 1,
                'message' => 'Retrieval successful',
                'results' => CategoryResource::collection($results),
            ], Response::HTTP_OK);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return response([ 'category' => new CategoryResource($category), 'message' => 'Retrieved successfully'], 200);
    }

}

app/Http/Controllers/Api/Trivia/QuestionController.php
<?php

namespace App\Http\Controllers\Api\Trivia;

use App\Models\Trivia\Question;
use App\Http\Controllers\Controller;
use App\Http\Resources\QuestionResource;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class QuestionController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $results = Question::where('category', $request->category)->where('level', $request->level)->take($request->limit + 1)->get();

        if (!$results) 
            return response()->json([
                'status' => 0,
                'message' => 'Retrieval unsuccessful',
            ], Response::HTTP_BAD_REQUEST);
        else 
            return response()->json([
                'status' => 1,
                'message' => 'Retrieval successful',
                'results' => $results
            ], Response::HTTP_OK);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        if (!$question)
            return response([
                'status' => 0,
                'message' => 'Retrieval unsuccessful'
            ], Response::HTTP_BAD_REQUEST);
        else
            return response([
                'status' => 1,
                'message' => 'Retrieval successful',
                'question' => new QuestionResource($question), 
            ], Response::HTTP_OK);
    }

}

app/Http/Controllers/Api/Trivia/TriviaController.php
<?php

namespace App\Http\Controllers\Api\Trivia;

use App\Http\Controllers\Controller;
use App\Models\Trivia\Trivia;
use App\Http\Resources\TriviaResource;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class TriviaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $trivias = Trivia::all();
        return response([ 'trivias' => TriviaResource::collection($trivias), 'message' => 'Retrieved successfully'], 200);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $validator = Validator::make($data, [
            'name' => 'required|max:255',
            'year' => 'required|max:255',
            'company_headquarters' => 'required|max:255',
            'what_company_does' => 'required'
        ]);

        if($validator->fails()){
            return response(['error' => $validator->errors(), 'Validation Error']);
        }

        $trivia = Trivia::create($data);

        return response([ 'trivia' => new TriviaResource($trivia), 'message' => 'Created successfully'], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Trivia  $trivia
     * @return \Illuminate\Http\Response
     */
    public function show(Trivia $trivia)
    {
        return response([ 'trivia' => new TriviaResource($trivia), 'message' => 'Retrieved successfully'], 200);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Trivia  $trivia
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Trivia $trivia)
    {

        $trivia->update($request->all());

        return response([ 'trivia' => new TriviaResource($trivia), 'message' => 'Retrieved successfully'], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Model\Trivia $trivia
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Trivia $trivia)
    {
        $trivia->delete();

        return response(['message' => 'Deleted']);
    }
}

app/Http/Controllers/Trivia/CategoryController.php
<?php

namespace App\Http\Controllers\Trivia;

use App\Models\Trivia\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the categories
     *
     * @param  \App\Models\Category  $model
     * @return \Illuminate\View\View
     */
    public function index()
    {
        //$categories = Category::select(['*', DB::raw('(SELECT COUNT(*) FROM words WHERE words.trivia_cart = categories.id) as words')])->get();
        $categories = Category::paginate(20);
        return view('categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $rq
     * @return \Illuminate\Http\Response
     */
    public function store(Request $rq)
    {
        if ($rq->hasFile('image')) {
            if ($rq->file('image')->isValid()) {
                $imagename = time();
                $extension = $rq->image->extension();
                $rq->image->storeAs('images', $imagename . "." . $extension, ['disk' => 'media']);
                $url = 'media/images/' . $imagename . "." . $extension;
                
                Category::create([
                    'number' => $rq->get('number'),
                    'title' => $rq->get('title'),
                    'description' => $rq->get('description'),
                    'icon' => $url
                ]);
            }
        }
        else 
            Category::create($rq->all());
        return redirect()->route('categories.index')->with('success', 'Category created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function view(Category $category)
    {
        return view('categories.view', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('categories.edit', compact('category'));
    }

    /**
     * Update the resource
     *
     * @param  \App\Http\Requests\Request  $rq
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $rq, Category $category)
    {
        try {

            $category->update($rq->all());
            return redirect()->route('categories.index')->with('success', 'Category updated successfully.');
        } catch (\Exception $exception) {
            return redirect()->back()->withError('Error while updating Category');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Apptime  $apptime
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        File::delete(public_path() . '/' . $category->icon);
        $category->delete();
        return redirect()->route('categories.index')->with('success', 'Category deleted successfully');
    }
}

resources/views/trivia/edit.blade.php
@extends('layouts.app', ['title' => __('Trivia Details')])

@section('content')
    @include('partials.header', [
        'title' => __('Edit Trivia: ') . $trivia->title,
        'meaning' => $trivia->meaning,
    ])   

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-4 order-xl-2 mb-5 mb-xl-0">
                
            </div>
            <div class="col-xl-8 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-body">
                        <form method="post" action="{{ route('trivia.update', $trivia) }}" autocomplete="off" enctype="multipart/form-data">
                            @csrf
                            
                            <div class="card-header border-0">
                                <div class="row align-items-center">
                                     <div class="col-8"> </div>
                                    <div class="col-4 text-right">
                                        <a href="{{ route('trivia.index') }}" class="btn btn-sm btn-primary">Back to Trivia</a>
                                    </div>
                                </div>
                            </div>

                            @if (session('status'))
                                <div class="alert alert-success alert-dismissible fade show" role="alert">
                                    {{ session('status') }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            @endif

                            <div class="pl-lg-4">                                
                                <div class="form-group{{ $errors->has('title') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-title">{{ __('Trivia Name') }}</label>
                                    <input type="text" name="title" id="input-title" class="form-control form-control-alternative{{ $errors->has('title') ? ' is-invalid' : '' }}" value="{{ $trivia->title }}">

                                    @if ($errors->has('title'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('title') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                
                                <div class="form-group{{ $errors->has('meaning') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-meaning">{{ __('Trivia Meaning (Optional)') }}</label>
                                    <input type="text" name="meaning" id="input-meaning" class="form-control form-control-alternative{{ $errors->has('meaning') ? ' is-invalid' : '' }}" value="{{ $trivia->meaning }}">

                                    @if ($errors->has('meaning'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('meaning') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save Changes') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/trivia/index.blade.php
@extends('layouts.app', ['title' => __('Trivia Profile')])

@section('content')
    @include('partials.header', [
        'title' => __('Site Trivias'),
    ])   

<div class="container-fluid mt--7">
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">Site Trivias</h3>
                        </div>
                        <div class="col-4 text-right">
                            <a href="{{ route('trivia.create') }}" class="btn btn-sm btn-primary">Add a Trivia</a>
                        </div>
                    </div>
                </div>
                
                <div class="col-12"></div>

                @if (session('status'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session('status') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif

                <div class="table-responsive">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Location</th>
                                <th scope="col">Email</th>
                                <th scope="col">Mobile</th>
                                <th scope="col">Creation Date</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                             @foreach ($trivia as $trivial)
                            <tr>
                                <td>{{ $trivial->name }}, {{ $trivial->title }}</td>
                                <td>{{ $trivial->town }}, {{ $trivial->country }}</td>
                                <td>
                                    <a href="mailto:#">{{ $trivial->email }}</a>
                                </td>
                                <td>
                                    <a href="mobile:#">{{ $trivial->mobile }}</a>
                                </td>
                                <td>{{ $trivial->created_at }}</td>
                                <td class="text-right">
                                    <div class="dropdown">
                                        <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-ellipsis-v"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                            <a class="dropdown-item" href="{{ route('trivia.edit', $trivial->id) }}">Edit</a>
                                            <a class="dropdown-item" href="">Delete</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer py-4">
                    <nav class="d-flex justify-content-end" aria-label="...">
                        
                    </nav>
                </div>
            </div>
        </div>
    </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection