routes/web.php
<?php

use Illuminate\Http\File;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('privacy-policy', 'App\Http\Controllers\PrivacyController@index');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {  
    Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');

	Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', 'App\Http\Controllers\UserController@index')->name('index');
        Route::get('edit/{user}', 'App\Http\Controllers\UserController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\UserController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\UserController@store')->name('store');
        Route::post('u/{user}/update', 'App\Http\Controllers\UserController@update')->name('update');
        Route::get('d/{user}/delete', 'App\Http\Controllers\UserController@destroy')->name('delete');
    });

    Route::get('profile', 'App\Http\Controllers\ProfileController@edit')->name('profile.edit');
    Route::put('profile', 'App\Http\Controllers\ProfileController@update')->name('profile.update');
    Route::put('profile/password', 'App\Http\Controllers\ProfileController@password')->name('profile.password');

    Route::group(['prefix' => 'words', 'as' => 'words.'], function () {
        Route::get('/', 'App\Http\Controllers\Data\WordController@index')->name('index');
        Route::get('view/{word}', 'App\Http\Controllers\Data\WordController@view')->name('view');
        Route::get('edit/{word}', 'App\Http\Controllers\Data\WordController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\Data\WordController@create')->name('create');
        Route::get('search', 'App\Http\Controllers\Data\WordController@search')->name('search');
        Route::get('find', 'App\Http\Controllers\Data\WordController@find')->name('find');
        Route::post('store', 'App\Http\Controllers\Data\WordController@store')->name('store');
        Route::post('u/{word}/update', 'App\Http\Controllers\Data\WordController@update')->name('update');
        Route::get('d/{word}/delete', 'App\Http\Controllers\Data\WordController@destroy')->name('delete');
    });

    Route::group(['prefix' => 'proverbs', 'as' => 'proverbs.'], function () {
        Route::get('/', 'App\Http\Controllers\Data\ProverbController@index')->name('index');
        Route::get('edit/{proverb}/proverb', 'App\Http\Controllers\Data\ProverbController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\Data\ProverbController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\Data\ProverbController@store')->name('store');
        Route::post('u/{proverb}/update', 'App\Http\Controllers\Data\ProverbController@update')->name('update');
        Route::get('d/{proverb}/delete', 'App\Http\Controllers\Data\ProverbController@destroy')->name('delete');
    });

    Route::group(['prefix' => 'sayings', 'as' => 'sayings.'], function () {
        Route::get('/', 'App\Http\Controllers\Data\SayingController@index')->name('index');
        Route::get('edit/{saying}', 'App\Http\Controllers\Data\SayingController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\Data\SayingController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\Data\SayingController@store')->name('store');
        Route::post('u/{saying}/update', 'App\Http\Controllers\Data\SayingController@update')->name('update');
        Route::get('d/{saying}/delete', 'App\Http\Controllers\Data\SayingController@destroy')->name('delete');
    });

    Route::group(['prefix' => 'idioms', 'as' => 'idioms.'], function () {
        Route::get('/', 'App\Http\Controllers\Data\IdiomController@index')->name('index');
        Route::get('edit/{idiom}', 'App\Http\Controllers\Data\IdiomController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\Data\IdiomController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\Data\IdiomController@store')->name('store');
        Route::post('u/{idiom}/update', 'App\Http\Controllers\Data\IdiomController@update')->name('update');
        Route::get('d/{idiom}/delete', 'App\Http\Controllers\Data\IdiomController@destroy')->name('delete');
    });

    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
        Route::get('/', 'App\Http\Controllers\Trivia\CategoryController@index')->name('index');
        Route::get('edit/{category}', 'App\Http\Controllers\Trivia\CategoryController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\Trivia\CategoryController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\Trivia\CategoryController@store')->name('store');
        Route::post('u/{category}/update', 'App\Http\Controllers\Trivia\CategoryController@update')->name('update');
        Route::get('d/{category}/delete', 'App\Http\Controllers\Trivia\CategoryController@destroy')->name('delete');
    });

    Route::group(['prefix' => 'trivia', 'as' => 'trivia.'], function () {
        Route::get('/', 'App\Http\Controllers\Trivia\TriviaController@index')->name('index');
        Route::get('edit/{trivia}', 'App\Http\Controllers\Trivia\TriviaController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\Trivia\TriviaController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\Trivia\TriviaController@store')->name('store');
        Route::post('u/{trivia}/update', 'App\Http\Controllers\Trivia\TriviaController@update')->name('update');
        Route::get('d/{trivia}/delete', 'App\Http\Controllers\Trivia\TriviaController@destroy')->name('delete');
    });
    
    Route::group(['prefix' => 'questions', 'as' => 'questions.'], function () {
        Route::get('/', 'App\Http\Controllers\Trivia\QuestionController@index')->name('index');
        Route::get('view/{question}', 'App\Http\Controllers\Trivia\QuestionController@view')->name('view');
        Route::get('edit/{question}', 'App\Http\Controllers\Trivia\QuestionController@edit')->name('edit');
        Route::get('create/{word}', 'App\Http\Controllers\Trivia\QuestionController@create')->name('create');
        Route::get('search', 'App\Http\Controllers\Trivia\QuestionController@search')->name('search');
        Route::post('store', 'App\Http\Controllers\Trivia\QuestionController@store')->name('store');
        Route::post('u/{question}/update', 'App\Http\Controllers\Trivia\QuestionController@update')->name('update');
        Route::get('d/{question}/delete', 'App\Http\Controllers\Trivia\QuestionController@destroy')->name('delete');
    });

	Route::get('leaderboard', function () {
        return view('pages.upgrade');
    })->name('leaderboard');
});

Route::get('storage/{filename}', function ($filename) {
    $path = storage_path('public/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

app/Models/Trivia/Question.php
<?php

namespace App\Models\Trivia;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'userid', 'category', 'level', 'title', 'answer', 'option1', 'option2', 'option3', 'option4',
    ];

}

app/Http/Controllers/Api/Trivia/QuestionController.php
<?php

namespace App\Http\Controllers\Api\Trivia;

use App\Models\Trivia\Question;
use App\Http\Controllers\Controller;
use App\Http\Resources\QuestionResource;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class QuestionController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $results = Question::where('category', $request->category)->where('level', $request->level)->take($request->limit + 1)->get();

        if (!$results) 
            return response()->json([
                'status' => 0,
                'message' => 'Retrieval unsuccessful',
            ], Response::HTTP_BAD_REQUEST);
        else 
            return response()->json([
                'status' => 1,
                'message' => 'Retrieval successful',
                'results' => $results
            ], Response::HTTP_OK);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        if (!$question)
            return response([
                'status' => 0,
                'message' => 'Retrieval unsuccessful'
            ], Response::HTTP_BAD_REQUEST);
        else
            return response([
                'status' => 1,
                'message' => 'Retrieval successful',
                'question' => new QuestionResource($question), 
            ], Response::HTTP_OK);
    }

}

app/Http/Controllers/Trivia/QuestionController.php
<?php

namespace App\Http\Controllers\Trivia;

use App\Models\Data\Word;
use App\Models\Trivia\Category;
use App\Models\Trivia\Question;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class QuestionController extends Controller
{
    
    /**
     * search a listing of the questions
     *
     * @param  \Illuminate\Http\Request  $rq
     * @return \Illuminate\Http\Response
     */

    public function search(Request $request){
        
        if($request->ajax()) {
          
            $data = Question::where('title', 'LIKE', $request->searchQry.'%')->get();
           
            $output = '';
           
            if (count($data)>0) {              
                $output = '<div class="table-responsive">
                <table class="table align-items-center table-flush">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Question</th>
                            <th scope="col">Meaning</th>
                            <th scope="col">Synonyms</th>
                            <th scope="col">Conjugation</th>
                            <th scope="col">Searched</th>
                            <th scope="col">T.Cart</th>
                            <th scope="col">T.Level</th>
                            <th scope="col">T.Attempts</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>';          
                foreach ($data as $question){
                    $output .= '<tr onclick="window.location.href = \'questions/view/' . $question->id . '\';" style="cursor: pointer;">
                        <td align="right">' . $question->id . '.</td>
                        <td valign="top">' . $question->title . '</td>
                        <td style="white-space: normal;">' . $question->meaning . '</td>
                        <td style="white-space: normal;">' . $question->synonyms . '</td>
                        <td style="white-space: normal;">' . $question->conjugation . '</td>
                        <td align="right"></td>
                        <td align="right"></td>
                        <td align="right"></td>
                        <td align="right"></td>
                        <td class="text-right">
                            <div class="dropdown">
                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-ellipsis-v"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                <a class="dropdown-item" href="questions/edit/' . $question->id . '">Edit Question</a>
                                <a class="dropdown-item" href="questions/delete/' . $question->id . '" onclick="return confirm(\'Are you sure you want to delete: ' . $question->name . ' from the system? \nBe careful, this action can not be reversed.\')">Delete Question</a>
                                </div>
                            </div>
                        </td>
                    </tr>';
                }        
                $output .= '</tbody>
                </table>                
            </div>';
            }
            else {             
                $output .= '<h3>No results</h3>';
            }           
            return $output;
        }
    }

    /**
     * Display a listing of the questions
     *
     * @param  \App\Models\Question  $model
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $questions = Question::paginate(20);
        return view('questions.index', compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Word $word)
    {
        $categories = Category::all();
        $levels = [
            1 => 'Level 1',
            2 => 'Level 2',
            3 => 'Level 3',
            4 => 'Level 4',
            5 => 'Level 5',
            6 => 'Level 6',
            7 => 'Level 7',
            8 => 'Level 8',
            9 => 'Level 9',
            10 => 'Level 10',
        ];
        return view('questions.create', compact('word', 'levels', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $rq
     * @return \Illuminate\Http\Response
     */
    public function store(Request $rq)
    {
        try {
            $title = $rq['title1'];
            $answer = $rq['answer1'];

            if ($rq['format'] == 2) {
                $title = $rq['title2'];
                $answer = $rq['answer2'];
            }

            Question::create([
                'userid' => auth()->user()->id,
                'category' => $rq['category'],
                'level' => $rq['level'],
                'title' => $title,
                'answer' => $answer,
                'option1' => $rq['option1'],
                'option2' => $rq['option2'],
                'option3' => $rq['option3'],
                'option4' => $rq['option4'],
            ]);
            return redirect()->route('words.index')->with('success', 'Question created successfully.');
        } catch (\Exception $exception) {
            return redirect()->back()->withError('Error while creating Question');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function view(Question $question)
    {
        $categories = Category::all();
        return view('questions.view', compact('question', 'categories'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        $categories = Category::all();
        $levels = [
            1 => 'Level 1',
            2 => 'Level 2',
            3 => 'Level 3',
            4 => 'Level 4',
            5 => 'Level 5',
            6 => 'Level 6',
            7 => 'Level 7',
            8 => 'Level 8',
            9 => 'Level 9',
            10 => 'Level 10',
        ];
    
        
        $answers = [$question->option1, $question->option2, $question->option3, $question->option4 ];
        return view('questions.edit', compact('question', 'answers', 'levels', 'categories'));
    }

    /**
     * Update the resource
     *
     * @param  \App\Http\Requests\Request  $rq
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $rq, Question $question)
    {
        try {
            $question->update($rq->all());
            return redirect()->route('questions.index')->with('success', 'Question updated successfully.');
        } catch (\Exception $exception) {
            return redirect()->back()->withError('Error while updating Question');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Apptime  $apptime
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        $question->delete();
        return redirect()->route('questions.index')->with('success', 'Question deleted successfully');
    }
}

resources/views/questions/create.blade.php
<?php 
    $html_options = '';

    for ($i = 1; $i <= 4; $i++)
    {
        $html_options .= '<div class="card bg-white shadow" style="margin-bottom: 10px;">
                        <div class="card-body">
                            <b> Option '. $i .'</b>: <span style="cursor: pointer;" onclick="showOrHide(\'searching'. $i .'\', 1)">Search Now</span>
                            <div id="searching' . $i .'" class="card bg-secondary" style="padding: 10px;margin-bottom: 10px;display: none;">
                                <input id="search'. $i .'" name="search'. $i .'" class="form-control" type="search" placeholder="Search" onkeyup="searchNow('. $i .')">
                                <div id="results'. $i .'"></div>
                            </div>
                            <table>
                                <tr>
                                    <td style="width: 100%;">
                                        <textarea name="option'. $i .'" id="option1" class="form-control"></textarea>
                                    </td>
                                    <td>
                                        <span class="btn btn-success" onclick="setOption('. $i .')">Done</span>
                                        <span class="btn btn-danger" onclick="clearOption('. $i .')">Clear</span>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>';
    }

?>
@extends('layouts.app', ['title' => __('Question Details')])

@section('content')
    @include('partials.header', [
        'title' => __('Create a New Question Based on: ' . $word->title),
        'description' => __('Meaning: ' . $word->meaning . '; Synonyms: ' . $word->synonyms),
    ])   

    <div class="container-fluid mt--7">
        
        <form method="post" action="{{ route('questions.store') }}">
            @csrf
            <div class="row">
                <div class="col-xl-12 order-xl-1">
                    <div class="card bg-secondary shadow">
                        <div class="card-body bg-white border-0">
                            <div class="row">
                                <div class="col-xl-3 order-xl-1" style="text-align: center;">
                                    <label> <b>Question Category</b> </label>
                                </div>
                                <div class="col-xl-3 order-xl-1">
                                    <div class="form-group">
                                        <select class="form-control custom-select" name="category" required>
                                        @foreach ($categories as $category )
                                            <option value="{{ $category->id }}"> {{ $category->title }} </option>  
                                        @endforeach
                                        </select>
                                    </div>
                                    @if ($errors->has('category'))
                                        <span class="invalid-feedback" style="display: block;" role="alert">
                                            <strong>{{ $errors->first('category') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="col-xl-3 order-xl-1" style="text-align: center;">
                                    <label> <b>Question Level</b> </label>
                                </div>

                                <div class="col-xl-3 order-xl-1">
                                    <div class="form-group">
                                        <select class="form-control custom-select" name="level" required>
                                        @foreach ($levels as $index => $level )
                                            <option value="{{ $index }}"> {{ $level }} </option>  
                                        @endforeach
                                        </select>
                                    </div>
                                    @if ($errors->has('level'))
                                        <span class="invalid-feedback" style="display: block;" role="alert">
                                            <strong>{{ $errors->first('level') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>     
            </div>
            <br>

            <div class="row">
                <div class="col-xl-6 order-xl-1">
                    <div class="card bg-secondary shadow">
                        <div class="card-header bg-white border-0">
                            <div class="row align-items-center">
                                <h2 class="mb-0">Question Format</h2>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="pl-lg-4">
                                
                                <div class="card bg-white shadow">
                                    <div class="card-body">
                                        <input type="radio" name="format" id="format1" value="1" checked required>
                                        <label for="format1" style="width: 90%"> Format 1</label>
                                        <div class="card bg-secondary" style="padding: 10px;margin-bottom: 10px;">
                                            <b>The Question</b>
                                            <textarea name="title1" id="input-title1" class="form-control" required>{{ $word->title }}</textarea>
                                        </div>
                                        <div class="card bg-secondary" style="padding: 10px;">
                                            <b>The Answer</b>
                                            <textarea name="answer1" id="input-answer1" class="form-control" required>{{ $word->meaning }}</textarea>
                                        </div>
                                    </div>
                                </div>
                                <br>
                                
                                <div class="card bg-white shadow">
                                    <div class="card-body">
                                        <input type="radio" name="format" id="format2" value="2" required>
                                        <label for="format2" style="width: 90%"> Format 2 </label>
                                        <div class="card bg-secondary" style="padding: 10px;margin-bottom: 10px;">
                                            <b>The Question</b>
                                            <textarea name="title2" id="input-title2" class="form-control" required>{{ $word->meaning }}</textarea>
                                        </div>
                                        <div class="card bg-secondary" style="padding: 10px;">
                                            <b>The Answer</b>
                                            <textarea name="answer2" id="input-answer2" class="form-control" required>{{ $word->title }}</textarea>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-6 order-xl-1">
                    <div class="card bg-secondary shadow">
                        <div class="card-header bg-white border-0">
                            <div class="row align-items-center">
                                <h2 class="mb-0">Question Options</h2>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="pl-lg-4">
                              <?php echo $html_options ?>
                            </div>
                        </div>
                    </div>
                </div>
                          
            </div>

            <div class="row">
                <div class="col-12 text-center">
                    <button type="submit" class="btn btn-success mt-4">{{ __('Create Question') }}</button>
                </div>
            </div>
        </form>  
        
        @include('layouts.footers.auth')
    </div>
@endsection

@push('js_scripts')
    @once        
        <script type="text/javascript">
        function searchNow(option) {                
            var format = $('#format').val();
            var query = $('#search' + option).val();

            $.ajax({            
                url:"{{ route('words.find') }}",        
                type:"GET",            
                data:{'findQry': format + ':' + query + ':' + option},
                
                success:function (data) {                
                    $('#results' + option).html(data);
                }
            });
        };

        function setValue(elem, data)
        {
            var optionelem = document.getElementById('option' + elem);
            optionelem.value = data;
        }

        function setOption(option)
        {
            showOrHide('searching' + option, 0);
            $('#results' + option).html('');
        }

        function clearOption(option)
        {
            document.getElementById('search' + option).value = '';
            document.getElementById('option' + option).value = '';
        }

        function showOrHide(elem, show)
        {
            if (show == 1)
                $('#' + elem).slideDown(400); //$('#' + elem).fadeIn();
            else
                $('#' + elem).slideUp(400); //$('#' + elem).fadeOut();
        }

        </script>    
    @endonce
@endpush

resources/views/questions/view.blade.php
<?php
    $varContents = $question->meaning;
    $varContents = str_replace("\\", "", $varContents);
    $varContents = str_replace('"', '', $varContents);
    $varContents = str_replace(',', ', ', $varContents);
    $varContents = str_replace('  ', ' ', $varContents);

    $varMeaning = explode("|", $varContents);
?>
@extends('layouts.app', ['title' => __('Question Profile')])

@section('content')
    @include('partials.header', [
        'title' => __('Neno') . ': '. $question->title,
    ])   

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-6">
                @foreach ($varMeaning as $meaning)
                    <div class="card bg-white shadow" style="margin-bottom: 10px;">
                        <div class="card-body">
                        <?php 
                            $varExtra = explode(":", $meaning);
                            if (sizeof($varExtra) == 2) {
                                echo " ~ " . $varExtra[0] . "<br><i>Mfano:</i> " . $varExtra[1];
                            }
                            else 
                                echo " ~ " . $meaning;
                        ?>
                        </div>
                    </div>
                @endforeach
                
            @if (isset($question->synonyms) && $question->synonyms)
                <?php
                    $varSynonyms = explode(",", $question->synonyms); 
                ?>
                <div class="card bg-white shadow">
                    <h3 style="margin: 10px 30px; ">VISAWE (<?php echo sizeof($varSynonyms); ?>)</h3>
                    <div class="card-body">
                        @foreach ($varSynonyms as $synonym)
                            {{ $synonym }}, 
                        @endforeach
                    </div>
                </div>
            @endif
            </div>
            <div class="col-xl-6">
                <div class="card bg-white shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-6">
                                <h2 class="mb-0">QUESTIONS</h2>
                            </div>

                            <div class="col-6 text-right">
                                <a href="{{ route('questions.create') }}" class="btn btn-sm btn-primary">NEW QUESTION</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        
                    </div>
                </div>
            </div>
            
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection